In [1]:
%ls

40 Python Interview and Answer_1556434162.pdf
AI_Python_1565122869.pdf
Algo/
Book/
Chapter-10---Normal-Crime_2015_Data-Mining-and-Predictive-Analysis.pdf*
Chapter-16---Future-Trends_2015_Data-Mining-and-Predictive-Analysis.pdf*
Chapter-2---Domain-Expertise_2015_Data-Mining-and-Predictive-Analysis.pdf*
Chapter-4---Process-Models-for-Data-Mining-and_2015_Data-Mining-and-Predicti.pdf*
Copyright_2015_Data-Mining-and-Predictive-Analysis.pdf*
Cora_competition.ipynb
Customer_Behaviour_1566388260.pdf
DATA_SCIENCE_INTERVIEW_QUESTIONS.pdf
Data science - copie.pdf
Data_Visualization_in_Practice_1566388340.pdf
Dedication_2015_Data-Mining-and-Predictive-Analysis.pdf*
Digital-Assets_2015_Data-Mining-and-Predictive-Analysis.pdf*
Feature_Engineering_for_Machine_Learning.pdf
Foreword_2015_Data-Mining-and-Predictive-Analysis.pdf*
Front-matter_2015_Data-Mining-and-Predictive-Analysis.pdf*
Great_EDA_Example_to_Follow_1565614953.pdf
How to playtech is usingg influxDB to monitor their distribueted systems.pdf
Index_2015_Data-Mining-and-Predictive-Analysis.pdf*
Introduction- Towards less casual causal inferences.pdf
Introduction_2015_Data-Mining-and-Predictive-Analysis.pdf*
Introduction_to_Python_for_Econometrics.pdf
JigSawCompetition.ipynb
Learn Python The Hard Way 3rd Edition V413HAV.pdf
ML_projects_1565796552.pdf
Machine Learning in python.pdf
Machine_Learning_Interpretability_1565244214.pdf
Machine_Learning_Projects_in_Python_1566111119.pdf
Machine_Learning_Yearning_1565872727.pdf
Mathematics_of_Machine_Learning_1566457065.pdf
Mongo.txt
MongoDB.ipynb
PYTHON_DATA_VISUALIZATION.pdf
Pandas_InfluxDB.ipunb
Plateforme-Schema.pdf
Practical Data Science Cookbook .pdf
Predict_Employee_Retention_Using_Keras_and_TensorFlow_1566551518.pdf
Preface_2015_Data-Mining-and-Predictive-Analysis.pdf*
Py/
Python Data for Developers.pdf
Python for Data Analysis.pdf
PythonScrip/
Python_1/
Python_Libraries_for_Interpretable_Machine_Learning_1565580024.pdf
Python_ML.xmind
Python_for_computational_science_and_eng.pdf
Quora.ipynb/
RandomForest.ipynb
Research_Assistant_in_Data_Science_1565077261.pdf
SCA_Pandas.ipynb
SCA_Pandsa_corrigé.ipynb
SaS_Learn.md
Super Crack Academy/
Supervised_Machine_Learning_1566211403.pdf
Test_technique_Antares.ipynb
Test_technique_GARBA_Moussa.ipynb
The Element of Statistical Learning .pdf
Titanic_challenge.ipynb
Titatanic_Overfitting_Underfitting.ipynb
Two_sigma_competition.ipynb
UDF_ARMA.ipynb
Untitled.ipynb
Untitled1.ipynb
WhatsApp Chat - Almajiri Child Rights.zip
XGBoost.pdf
XGBoost_regression [Enregistré automatiquement].pptx
XGBoost_regression.pptx
XGBoost_titanic-classification-regression.ipynb
bank/
bank-additional/
beginners-basic-workflow-introduction.ipynb
comment_XGboost.docx
competitive-data-science-predict-future-sales/
eda-feature-engineering-and-everything.ipynb
house-prices-advanced-regression-techniques/
house-prices-advanced-regression-techniques.ipynb
house-prices-begginer-top-7.ipynb
kaggleATP.ipynb
nyc-taxi-trip-duration/
periscope-analytics.csv
predictions-of-nyc-taxi-trip-duration-edaongam.ipynb
seaborn-tutorial.ipynb
search-08-24-19-030609.csv
simple-eda-two-sigma.ipynb
tatsmodels- Econometric and Statistical Modeling with Python.pdf
titanic/
titanic-classification-comprehensive-modeling.ipynb
titanic-data-eda-by-r.irnb
two-sigma-financial-news/

In [2]:
import pandas as pd
data  = pd.read_csv('search-08-24-19-030609.csv')

In [5]:
data.head()

,id,idno,title,nation,authoring_entity,year_start,year_end,created,changed
0,3246,AFG_2017_FINDEX_v02_M,Global Financial Inclusion (Global Findex) Dat...,Afghanistan,"Development Research Group, Finance and Privat...",2017,2017,Oct-18-18,Oct-31-18
1,2374,AFG_2014_FINDEX_v01_M,Global Financial Inclusion (Global Findex) Dat...,Afghanistan,"Development Research Group, Finance and Privat...",2014,2014,Oct-28-15,Oct-29-15
2,1117,AFG_2011_FINDEX_v02_M,Global Financial Inclusion (Global Findex) Dat...,Afghanistan,"Development Research Group, Finance and Privat...",2011,2011,Dec-12-12,Apr-15-15
3,3247,ALB_2017_FINDEX_v02_M,Global Financial Inclusion (Global Findex) Dat...,Albania,"Development Research Group, Finance and Privat...",2017,2017,Oct-18-18,Oct-31-18
4,2376,ALB_2014_FINDEX_v01_M,Global Financial Inclusion (Global Findex) Dat...,Albania,"Development Research Group, Finance and Privat...",2014,2014,Oct-28-15,Oct-29-15

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 436 entries, 0 to 435
Data columns (total 9 columns):
id                  436 non-null int64
idno                436 non-null object
title               436 non-null object
nation              436 non-null object
authoring_entity    436 non-null object
year_start          436 non-null int64
year_end            436 non-null int64
created             436 non-null object
changed             436 non-null object
dtypes: int64(3), object(6)
memory usage: 30.7+ KB

In [7]:
#checking for null value counts in each column
data.isnull().sum()

id                  0
idno                0
title               0
nation              0
authoring_entity    0
year_start          0
year_end            0
created             0
changed             0
dtype: int64

In [ ]:
f,ax=plt.subplots(1,3,figsize=(18,5))
data[['tittle','idno']].groupby(['Sex']).mean().plot.bar(ax=ax[0])
ax[0].set_title('Fraction of Survival with respect to Sex')
sns.countplot('Sex',hue='Survived',data=data,ax=ax[1])
ax[1].set_title('Survived vs Dead counts with respect to Sex')
sns.barplot(x="Sex", y="Survived", data=data,ax=ax[2])
ax[2].set_title('Survival by Gender')
plt.show()